spring.application.name=peoplecounter

# ==============================
# DataSource Configuration
# ==============================
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# ==============================
# Optional: JPA / Hibernate Settings
# ==============================
# Jika Anda menggunakan Spring Data JPA, bisa tambahkan:

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-stacktrace=never

api.key=${API_KEY}

server.port=8080
server.address=0.0.0.0


# application.properties
# Waktu maksimum (ms) menunggu koneksi dari pool sebelum timeout
spring.datasource.hikari.connection-timeout=30000

# Waktu (ms) sebelum koneksi dianggap idle dan di?evict
spring.datasource.hikari.idle-timeout=600000

spring.main.log-startup-info=false




sarinah-portal.base-url=https://sarinahportal.co.id/api/public
sarinah-portal.barcode.url=${sarinah-portal.base-url}/product_by_barcode
sarinah-portal.loyalty.url=${sarinah-portal.base-url}/member_loyalty
sarinah-portal.pos-order-history.url=${sarinah-portal.base-url}/pos_order_history
sarinah-portal.journal-entries-coa-harmonisasi.url=${sarinah-portal.base-url}/journal_entries_coa_harmonisasi

# HTTP Client settings
http.client.max-connections=300
http.client.max-per-route=100
http.client.connection-request-timeout=20000
http.client.connect-timeout=20000
http.client.read-timeout=20000


app.jwt.secret=change-this-secret-to-a-very-long-random-string-please-1234567890
app.jwt.issuer=sarinah-promis
app.jwt.access-ttl=PT5M
app.jwt.refresh-ttl=360


spring.thymeleaf.prefix= classpath:/templates/
spring.thymeleaf.suffix= .html

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


spring.thymeleaf.cache=false

server.forward-headers-strategy=framework













