spring.application.name=peoplecounter

# ==============================
# DataSource Configuration
# ==============================
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ==============================
# Optional: JPA / Hibernate Settings
# ==============================
# Jika Anda menggunakan Spring Data JPA, bisa tambahkan:

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.error.include-stacktrace=never

api.key=${API_KEY}

server.port=8080
server.address=0.0.0.0


# application.properties
# Waktu maksimum (ms) menunggu koneksi dari pool sebelum timeout
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.initialization-fail-timeout=1

spring.main.log-startup-info=false




sarinah-portal.base-url=https://sarinahportal.co.id/api/public
dev.sarinah-portal.base-url=https://192.168.70.98/api/public
sarinah-portal.barcode.url=${sarinah-portal.base-url}/product_by_barcode
sarinah-portal.loyalty.url=${sarinah-portal.base-url}/member_loyalty
sarinah-portal.pos-order-history.url=${sarinah-portal.base-url}/pos_order_history
sarinah-portal.journal-entries-coa-harmonisasi.url=${sarinah-portal.base-url}/journal_entries_coa_harmonisasi
sarinah-portal.pos.order.rating.url = ${sarinah-portal.base-url}/pos_order_rating
sarinah-portal.product_inj.url = ${sarinah-portal.base-url}/product_inj
sarinah-portal.order_refferal.url = ${sarinah-portal.base-url}/pos_order_refferal_inj
sarinah-portal.total-spender.url = ${sarinah-portal.base-url}/get_customer_with_sum_amount_total
api.base-url=

injourney-portal.base-url = https://integrated.injourney.id
injourney-portal.employee-login.url = ${injourney-portal.base-url}/employee/checkLogin
injourney-portal.employee-data-karyawan.url =${injourney-portal.base-url}/employee/dataKaryawanPersonalInfo



# HTTP Client settings
http.client.max-connections=300
http.client.max-per-route=100
http.client.connection-request-timeout=5000
http.client.connect-timeout=10000
http.client.read-timeout=60000


app.jwt.secret=change-this-secret-to-a-very-long-random-string-please-1234567890
app.jwt.issuer=sarinah-promis
app.jwt.access-ttl=PT5M
app.jwt.refresh-ttl=360


spring.thymeleaf.prefix= classpath:/templates/
spring.thymeleaf.suffix= .html

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


spring.thymeleaf.cache=false

server.forward-headers-strategy=framework

# Cloudinary
cloudinary.cloud-name=dvbuxnr6q
cloudinary.api-key=526813947939542
cloudinary.api-secret=4qLleSL5TcSZCDFR5-dWcYYYffg
cloudinary.folder=images


# ============================================
# LDAP / Active Directory Configuration
# ============================================
# Sesuaikan dengan konfigurasi AD di osTicket screenshot

ldap.url=ldap://10.0.7.12:389
ldap.domain=sarinah.net
ldap.base-dn=DC=sarinah,DC=net

# disable manager bind
ldap.manager-dn=
ldap.manager-password=


# ldap.user-search-filter=(&(objectClass=user)(sAMAccountName={0}))
# ldap.user-search-base=DC=sarinah,DC=net

# ldap.group-search-base=OU=Groups,DC=sarinah,DC=net
# ldap.group-search-filter=(&(objectClass=group)(member={0}))

# ============================================
# Session Configuration
# ============================================
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict


logging.level.org.springframework.security=INFO
logging.level.org.springframework.ldap=INFO
logging.level.com.sarinah.portal=DEBUG


logging.level.org.springframework.security.ldap=DEBUG
logging.level.org.springframework.security.ldap.authentication.ad=DEBUG


portal.apps[0].id=osticket
portal.apps[0].name=Helpdesk (osTicket)
portal.apps[0].url=https://siap.sarinah.com/legal/
portal.apps[0].login-url=https://siap.sarinah.com/legal/login.php
portal.apps[0].icon=headset
portal.apps[0].description=Sistem Informasi Aduan dan Pelayanan
portal.apps[0].roles=
portal.apps[0].form-fields.luser=username
portal.apps[0].form-fields.lpasswd=password
portal.apps[0].form-fields.__CSRFToken__=FETCH_CSRF
portal.apps[0].form-fields.do=scplogin

portal.apps[1].id=odoo
portal.apps[1].name=Odoo ERP
portal.apps[1].login-url=https://odoo.sarinah.com/web/login
portal.apps[1].icon=database
portal.apps[1].description=Enterprise Resource Planning
portal.apps[1].roles=
portal.apps[1].form-fields.login=username
portal.apps[1].form-fields.password=password

portal.apps[2].id=odoo
portal.apps[2].name=ERP (Odoo)
portal.apps[2].url=https://erp.sarinah.net
portal.apps[2].icon=building
portal.apps[2].description=Enterprise Resource Planning
portal.apps[2].roles=ROLE_ADMIN

portal.apps[3].id=email
portal.apps[3].name=Email (Zimbra)
portal.apps[3].url=https://mail.sarinah.net
portal.apps[3].icon=mail
portal.apps[3].description=Email Korporat Sarinah
portal.apps[3].roles=ROLE_STAFF,ROLE_ADMIN







